import type { Expert, Pred, FeedItem, EventItem } from "@/types";

export const EXPERTS: Expert[] = [
  { rank:1, name:"VisionKing",  gk:"seer",      score:91.2, acc:"94.1", preds:412, subs:2840,
    cat:"코인", bio:"온체인 분석 + 거시경제 결합. 연속 12회 적중.",
    badges:["Sealed Eye","Seer 2026","Top 0.1%"],
    certs:[{q:"Q3 25",gk:"proven"},{q:"Q4 25",gk:"seer"},{q:"Q1 26",gk:"seer"},{q:"Q2 26",gk:"seer"}],
    qScores:[{q:"Q3-25",v:78},{q:"Q4-25",v:85},{q:"Q1-26",v:89},{q:"Q2-26",v:91}] },
  { rank:2, name:"OracleJi",    gk:"seer",      score:89.5, acc:"91.3", preds:387, subs:2210,
    cat:"주식", bio:"전직 퀀트. Fed 정책+섹터 로테이션 전문.",
    badges:["Sealed Eye","Seer 2026","Top 0.3%"],
    certs:[{q:"Q4 25",gk:"proven"},{q:"Q1 26",gk:"seer"},{q:"Q2 26",gk:"seer"}],
    qScores:[{q:"Q4-25",v:81},{q:"Q1-26",v:86},{q:"Q2-26",v:89}] },
  { rank:3, name:"KimOracle",   gk:"proven",    score:84.3, acc:"87.2", preds:284, subs:1204,
    cat:"정치", bio:"매크로 지표 기반 예측 전문. 분기 연속 Proven.",
    badges:["Proven 2026","Top 1%"],
    certs:[{q:"Q3 25",gk:"forecaster"},{q:"Q4 25",gk:"proven"},{q:"Q1 26",gk:"proven"},{q:"Q2 26",gk:"proven"}],
    qScores:[{q:"Q3-25",v:68},{q:"Q4-25",v:75},{q:"Q1-26",v:81},{q:"Q2-26",v:84}] },
  { rank:4, name:"SeoulSeer",   gk:"proven",    score:81.7, acc:"84.7", preds:198, subs:882,
    cat:"주식", bio:"채권 트레이더 출신. Fed 정책 예측 전문.",
    badges:["Proven 2026","Top 3%"],
    certs:[{q:"Q4 25",gk:"forecaster"},{q:"Q1 26",gk:"proven"},{q:"Q2 26",gk:"proven"}],
    qScores:[{q:"Q4-25",v:67},{q:"Q1-26",v:75},{q:"Q2-26",v:82}] },
  { rank:5, name:"CryptoMind",  gk:"forecaster",score:72.4, acc:"74.9", preds:89,  subs:0,
    cat:"코인", bio:"온체인 데이터 분석. Proven 도전 중.",
    badges:[],
    certs:[{q:"Q1 26",gk:"candidate"},{q:"Q2 26",gk:"forecaster"}],
    qScores:[{q:"Q1-26",v:58},{q:"Q2-26",v:72}] },
];

export const PREDS: Pred[] = [
  { id:1, cat:"코인",  stage:"active", q:"비트코인, 이번 주 10만 달러 돌파할 것인가?",
    A:"돌파한다", B:"못 한다", eA:"🚀", eB:"📉",
    p:18402, dl:"23:14:23", hot:true, agk:"seer", aName:"VisionKing",
    aScore:91.2, aAcc:"94.1", blind:true, price:300,
    myPred:null },
  { id:2, cat:"주식",  stage:"active", q:"삼성전자, 내일 상승 마감할 것인가?",
    A:"상승 마감", B:"하락 마감", eA:"📈", eB:"📉",
    p:9881, dl:"06:30:00", hot:false, agk:"proven", aName:"KimOracle",
    aScore:84.3, aAcc:"87.2", blind:true, price:100,
    myPred:null },
  { id:3, cat:"스포츠", stage:"verify", q:"손흥민, 이번 시즌 토트넘 잔류할 것인가?",
    A:"잔류", B:"이적", eA:"🤍", eB:"✈️",
    p:24110, dl:"검증중", hot:true, agk:"proven", aName:"SeoulSeer",
    aScore:81.7, aAcc:"84.7", blind:false, price:0,
    myPred:"A" },
  { id:4, cat:"이슈",  stage:"active", q:"2026 미국 중간선거, 민주당 하원 탈환 성공?",
    A:"탈환 성공", B:"탈환 실패", eA:"🫏", eB:"🐘",
    p:33401, dl:"47일", hot:true, agk:"seer", aName:"OracleJi",
    aScore:89.5, aAcc:"91.3", blind:true, price:300,
    myPred:null },
  { id:5, cat:"코인",  stage:"done", status:"revealed", q:"이더리움, 4월 3일 상승 마감?",
    A:"상승", B:"하락", eA:"📈", eB:"📉",
    p:7234, dl:"종료", hot:false,
    result:"A", aR:62, bR:38,
    totalP:7234, successP:4485, failP:2749,
    myPred:"A" },
];

export const FEED_ITEMS: FeedItem[] = [
  { id:1, author:"VisionKing",   agk:"seer",    cat:"코인",   dl:"23:14:23",
    score:91.2, acc:"94.1", preds:412, price:300, subscribeOnly:false,
    titleParts:["비트코인이 이번 주 안에 ", true, "달러를 돌파할 것이다."] },
  { id:2, author:"OracleJi",     agk:"seer",    cat:"주식",   dl:"06:30:00",
    score:89.5, acc:"91.3", preds:387, price:300, subscribeOnly:true,
    titleParts:["삼성전자 실적 발표 후 ", true, "% ", true, "할 것이다."] },
  { id:3, author:"KimOracle",    agk:"proven",  cat:"정치",   dl:"47일",
    score:84.3, acc:"87.2", preds:284, price:100, subscribeOnly:false,
    titleParts:["2026 중간선거 민주당 경합주 ", true, "석 이상 확보할 것이다."] },
  { id:4, author:"SeoulSeer",    agk:"proven",  cat:"주식",   dl:"06:30:00",
    score:81.7, acc:"84.7", preds:198, price:100, subscribeOnly:false,
    titleParts:["삼성전자가 한 달로 ", true, "% 상승할 것이다."] },
];

/* ── EVENTS ──────────────────────────────────────── */
export const EVENTS: EventItem[] = [
  {
    id:1, brand:"Tesla", sym:"TSLA", icon:"🚗", brandColor:"#E31937", logo:"tesla",
    duration:10, status:"live", deadline:"D-6",
    startDate:"2026.04.28", endDate:"2026.05.08",
    prizePool:2840000,
    desc:"Tesla 주가가 10일 동안 매일 상승할지 하락할지, 검증된 전문가들만 예측합니다.",
    experts:[
      { name:"VisionKing", gk:"seer",   score:91.2, correct:4, total:5, streak:3 },
      { name:"OracleJi",   gk:"seer",   score:89.5, correct:3, total:5, streak:1 },
      { name:"KimOracle",  gk:"proven", score:84.3, correct:3, total:5, streak:0 },
      { name:"SeoulSeer",  gk:"proven", score:81.7, correct:2, total:5, streak:0 },
    ],
    history:[
      { day:1, actual:"📈", date:"04.28" }, { day:2, actual:"📉", date:"04.29" },
      { day:3, actual:"📈", date:"04.30" }, { day:4, actual:"📈", date:"05.01" },
      { day:5, actual:"📉", date:"05.02" }, { day:6, actual:null, date:"05.03" },
    ],
  },
  {
    id:2, brand:"Samsung", sym:"005930", icon:"📱", brandColor:"#1428A0", logo:"samsung",
    duration:15, status:"live", deadline:"D-12",
    startDate:"2026.04.25", endDate:"2026.05.10",
    prizePool:1520000,
    desc:"삼성전자 주가의 15일 연속 상승/하락을 전문가들이 매일 예측합니다.",
    experts:[
      { name:"OracleJi",   gk:"seer",   score:89.5, correct:2, total:3, streak:2 },
      { name:"SeoulSeer",  gk:"proven", score:81.7, correct:2, total:3, streak:1 },
      { name:"KimOracle",  gk:"proven", score:84.3, correct:1, total:3, streak:0 },
    ],
    history:[
      { day:1, actual:"📈", date:"04.25" }, { day:2, actual:"📈", date:"04.26" },
      { day:3, actual:"📉", date:"04.27" }, { day:4, actual:null, date:"04.28" },
    ],
  },
  {
    id:3, brand:"Apple", sym:"AAPL", icon:"🍎", brandColor:"#555", logo:"apple",
    duration:30, status:"upcoming", deadline:"D+12",
    startDate:"2026.05.10", endDate:"2026.06.09",
    prizePool:0,
    desc:"Apple WWDC 전후 30일간 매일 주가 방향을 예측하는 초장기 배틀.",
    experts:[], history:[],
  },
];
